name: Continuous Deployment
on:
  push:
    branches:
      - develop

jobs:
  deployment:
    name: Deploy to GitHub Page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: copy package.json to public
        run: cp package.json ./public

      - name: Export
        run: yarn export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          commit_message: ${{ github.event.head_commit.message }}
