name: Continuous Integration
on: pull_request

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check modules
        run: yarn install --immutable --immutable-cache
      - name: Run unit tests
        run: yarn test
      - name: Run TypeScript check
        run: yarn tsc
  lint:
    name: Run ESLint with Reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Yarn 2 check modules
        run: yarn install --immutable --immutable-cache
      - run: yarn lint
      - name: Install eslint-formatter-rdjson
        run: yarn add -D eslint-formatter-rdjson
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run ESLint with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn eslint -f rdjson . | reviewdog -f=rdjson -reporter=github-pr-review
